### ISSUE TITLE
Add Type to semantic

### ISSUE THREAD

**Issue by palmerabollo** [gemsi/grok#10]
It would be great to use this tool to pipe lines into it and output the captured fields as json or any other standard representation. Something like this:

```bash
cat file.txt | grok -e "%{COMMONAPACHELOG}"
```
**Output:**
```
{"clientip":"127.0.0.1", "response": 404, "bytes": 207, ...}
```

**Comment by fxnn** [comment]
Sounds like an idea for a new github project :) A great idea, though!

**Comment by vjeantet** [comment]
Yes, it should be a new one, I'll push an alpha version tomorrow.

**Comment by palmerabollo** [comment]
I've created something here https://github.com/palmerabollo/grok/blob/master/grok.go. I'm not a Go expert but it seems to work. Any contributions are welcome.

It is not able to differentiate numbers from strings yet. So, for example, in this example:

```
echo "Hello 123" | grok -pattern="%{WORD:word} %{WORD:number:int}"
```

It writes ```{"number":"123","word":"Hello"}``` instead of ```{"number":123,"word":"Hello"}```

**Comment by vjeantet** [comment]
Nice @palmerabollo !

You may rename the tool as grok-cli cligrok groker grokli ?

**Comment by palmerabollo** [comment]
Done. I am not sure about whether gemsi/grok is able to detect field types. Apparently, it only extracts field names and values in a map. Could you confirm this? Thanks.

**Comment by vjeantet** [comment]
I confirm.

Also, I didn't know about this notation PATTERN:NAME:TYPE
If i use your example on the grok debugger, it does not work -> https://grokdebug.herokuapp.com

I would use something like ```%{WORD:word} %{NUMBER:number}```

**Comment by palmerabollo** [comment]
Yes, the [official grok docs](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html) say: *"Optionally you can add a data type conversion to your grok pattern. By default all semantics are saved as strings. If you wish to convert a semantic’s data type, for example change a string to an integer then suffix it with the target data type. For example %{NUMBER:num:int} which converts the num semantic from a string to an integer. Currently the only supported conversions are int and float."*

IMO that would be a great addition to gemsi/grok, because types are really important when you index data (for example in elascticsearch), which is my use case. Otherwise everything is indexed as a string and you lose the ability to do numerical calculations (avg, sum, etc).

**Comment by palmerabollo** [comment]
@fxnn @vjeantet Could you give me some hints on where to start if I wanted to implement the PATTERN:NAME:TYPE notation? Do you foresee any issues? Maybe the key-value map returned by ```grok.Parse()``` is a limitation to return both a value and a type.

**Comment by fxnn** [comment]
@palmerabollo Guess you'd have to use a `map[string]interface{}`, so that you're able to implement variable types.

**Comment by palmerabollo** [comment]
Thanks. @prep, you are also working on a fork of this project. Should I wait for your changes to be merged before I try to add a new function ```ParseToTypedValues``` able to handle types?

**Comment by vjeantet** [comment]
@prep, i'm ready to merge your Config Options struct implementation.

**Comment by prep** [comment]
@palmerabollo @vjeantet The problem with that is that my fork has a lot more changes than just the Config struct, as you [can see here](https://github.com/gemsi/grok/compare/master...prep:master).

It's mostly to have a 1-on-1 copy of the patterns compiled in (instead of the preprocessed version), but also some changes in documentation/comments, 1 or 2 new functions a few tweaks to the code as I was making my changes.

How do you want to do this?

**Comment by vjeantet** [comment]
Hello @prep, If you are OK, i'll try to pull your master and commit each change one by one 
Config Options Struct, Documentation tweaks, and at last i will check the way you handle patterns.

**Comment by prep** [comment]
@vjeantet oh sure, be my guest :-) To be honest, I didn't think you'd be interested in my changes as you went a different route with the Config stuff. If I had known, I'd have made a couple of PRs weeks ago.

**Comment by vjeantet** [comment]
@prep i did it.. not sure if the way I did it with git was the "way to go", but it works, i cherry picks the relevants commits.

I did not want to introduce the Config struct before needed, because it could break code from people using grok lib in their project.
But since i discovered that "vendoring" was possible with go, i am more available to introduce such kind of changes.

I also removed the preprocessed version of compiled in patterns. it's now easier to maintain and track pattern's changes.

Thanks for your work :+1: )

**Comment by palmerabollo** [comment]
I've been working with @lentregu these days in a new function able to parse types (int and float). Any feedback about the [proposed implementation](https://github.com/gemsi/grok/compare/master...palmerabollo:feature/ParseType) or alternative implementations are welcome.

It adds a "segmentType" when the pattern is denormalized to avoid losing the type:
```
replace = fmt.Sprintf("(?P<%s_%s>%s)", semantic, segmentType, storedPattern)
```
Example usages with [groker](https://github.com/palmerabollo/groker):

```
echo "Hello 123.7" | ./groker -pattern="%{WORD:word} %{GREEDYDATA:number:int}"
{"number":123,"word":"Hello"}

echo "Hello 123.7" | ./groker -pattern="%{WORD:word} %{GREEDYDATA:number:float}"
{"number":123.7,"word":"Hello"}

echo "Hello 123.7" | ./groker -pattern="%{WORD:word} %{GREEDYDATA:number}"
{"number":"123.7","word":"Hello"}
```

We have already merged @prep's changes into our branch. It is not finished yet. We still need to clean some code and add some tests.

**Comment by vjeantet** [comment]
Hello, @palmerabollo.

Does it works well with patterns which have "_" in named captures ? like 
```"AUDITLOGIN":     `type=%{WORD:audit_type} msg=audit\(%{CISCO_ACTION:action}```

What about adding a map to each pattern, referencing type informations ? 
This way we don't mix regex names with type information. and while parsing we will not have to test and convert each match, but only the ones referenced in the linked pattern map type information.

**Comment by palmerabollo** [comment]
Thanks for the feedback, @vjeantet.
It works with patterns with "_" in named captures because it takes the position of the last "_". We tried to use a different character ("#") at first, but it didn't work well.
We'll try to modify the implementation to add the map you mention.

**Comment by palmerabollo** [comment]
@vjeantet we have modified the implementation and added some unit tests. [PR sent](https://github.com/gemsi/grok/pull/11).

**Comment by vjeantet** [comment]
thank you @palmerabollo I'll look at it

**Comment by palmerabollo** [comment]
Fixed in https://github.com/gemsi/grok/pull/11

**Comment by palmerabollo** [comment]
We are already using grok in a fork of logstash-forwarder that allows users to format logs in the client side, before sending them to a remote endpoint. https://github.com/macvaz/logstash-forwarder/blob/master/formatter.go Thank you for your help making that possible.
