### ISSUE TITLE
rename constants in the form of "DefaultCapture", not "DEFAULTCAPTURE"

### ISSUE THREAD

**Issue by vjeantet** [gemsi/grok#7]
@prep feedback :
> A minor nitpick, but the norm in Go is to use constants in the form of "DefaultCapture", not "DEFAULTCAPTURE" ;-)

**Comment by vjeantet** [comment]
If i change the const names, it may break applications using Grok (like gowatch).

What do you think about this change

**Comment by fxnn** [comment]
The change is relatively new, and in the and, if a developer needs stable APIs, he *must* use vendoring (or another dependency management technique). Or to put it in another way: I think that we should never fear necessary (and worthy) change.

So, is it worth it? I personally don't care *that* much whether it's upper or camel, as long as it's consistent within the repository.

But maybe we could think about those names in general: Are `NamedCapture` and `DedaultCapture` good names? Maybe `AllCaptures` or `EveryCapture` would be more descriptive and future proof, and as far as I'm concerned, that is definitely not change being worth it.

**Comment by vjeantet** [comment]
To follow your proposals, I propose these constant names :
grok.NamedCaptures
grok.AllCaptures
grok.SkipDefaultPatterns

This will be the last constants names changes
