### ISSUE TITLE
Setting global options when creating the Grok instance.

### ISSUE THREAD

**Issue by vjeantet** [gemsi/grok#8]
This issue, to follow #5 discussion about options when starting Grok

What is the best way to handle configuration ?

**Comment by prep** [comment]
For what it's worth, I went with the suggestion I made in #5 by using a Config struct in my [fork](https://github.com/prep/grok) and I'm basing my own projects on that.

**Comment by vjeantet** [comment]
you suggestion was followed, as i pulled your code :)
